# Generated by Django 4.0.5 on 2022-06-21 14:44

from django.db import migrations, models
import utils.generators


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.CharField(max_length=300, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='community',
            name='picture',
            field=models.ImageField(blank=True, upload_to=utils.generators.generateNameFile, verbose_name='Imagem'),
        ),
    ]
