# Generated by Django 4.0.5 on 2022-07-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_alter_community_description_alter_community_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='isOwner',
            field=models.BooleanField(default=False),
        ),
    ]
