def partition_url(path_info):
    """
        Returns sections of a request url path.
    """

    # remove '' items generated by splitting the url.
    return [part for part in path_info.split('/') if part != '']
