# Generated by Django 4.0.5 on 2022-06-28 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='private',
        ),
        migrations.DeleteModel(
            name='RepositoryStar',
        ),
    ]
